Feature robin4routers
ffbsee/ffbsee-firmware pull request #103
Opened 2020-10-31 20:48 UTC by re4jh

reopening #97

2020-12-01 08:37 UTC, DEvil0000 requested changes

2020-12-01 08:37 UTC, DEvil0000 commented on files/usr/sbin/wgetspeedtest.sh
> +  echo $RESULTFF > /tmp/log/last_speedtest_ff_mbps.txt
mkdir -p mit allen pfaden die du verwenden willst wäre noch gut

2020-12-10 03:42 UTC, wolf128058 commented
ich schreib in den /tmp/log/
hab jetzt mal noch den /tmp/ zu den mkdir-calls hinzugefügt, oder meinst du noch was anderes?

2020-12-10 07:45 UTC, DEvil0000 commented
/tmp/log erzeugen wäre gut

10.12.2020 04:42:25 Jonas Hess aka Wolf <notifications@github.com>:

> ich schreib in den /tmp/log/
> hab jetzt mal noch den /tmp/ zu den mkdir-calls hinzugefügt, oder meinst du noch was anderes?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub[https://github.com/ffbsee/ffbsee-firmware/pull/103#issuecomment-742218416], or unsubscribe[https://github.com/notifications/unsubscribe-auth/AAZQPLV6EUW55LH763W75D3SUA7SBANCNFSM4TGDA5FQ].
>  [data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEIAAABCCAYAAADjVADoAAAAAXNSR0IArs4c6QAAAARzQklUCAgICHwIZIgAAAAnSURBVHic7cEBDQAAAMKg909tDwcUAAAAAAAAAAAAAAAAAAAAAPBjRFIAASHKmKkAAAAASUVORK5CYII=###24x24:true###][Tracking-Bild][https://github.com/notifications/beacon/AAZQPLRDIEFPDPB7CNB4VLDSUA7SBA5CNFSM4TGDA5F2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOFQ6VVMA.gif]
>

2020-12-10 09:42 UTC, DEvil0000 approved these changes

2021-01-03 16:38 UTC, merged