Update to 2.4.0
ffbsee/ffbsee-firmware pull request #106
Opened 2022-05-05 20:10 UTC by mart-ffbsee

includes new gluon patches and security fix

2022-05-05 22:16 UTC, DEvil0000 requested changes

2022-05-05 22:16 UTC, DEvil0000 commented on feeds.conf
> +src-git luci https://git.openwrt.org/project/luci.git;openwrt-22.03
der relevante patch ist auch in 19.07 ich find jetzt auf 22.03 zu gehen echt wild. sows muss man gut vorbereiten und testen. bitte 19.07 - gillt natürlich auch für hashes

2022-05-05 22:16 UTC, DEvil0000 commented on files/etc/config/freifunk
> +	option version '2.4.0'
die 2.4 hatten wir schonmal vergeben wurde aber nie ausgerollt. nimm bitte 2.5

2022-05-05 22:16 UTC, DEvil0000 commented on files/etc/uci-defaults/50_freifunk-setup
> +update_230() {
rename zu 240 bitte und skip von 230 funktion

2022-05-05 22:16 UTC, DEvil0000 commented on files/etc/uci-defaults/50_freifunk-setup
> +        cp /rom/etc/uhttpd.crt /etc/ 2> /dev/null
musst du die nicht auch wieder rein kopieren iwann?

2022-05-05 22:26 UTC, DEvil0000 commented on files/etc/config/freifunk
> +	option version '2.4.0'
mit 2.4.1 wäre ich auch fein

2022-05-05 22:28 UTC, DEvil0000 commented on files/etc/config/freifunk
> +	option version '2.4.0'
mit 2.4.1 wäre ich auch fein

2022-05-06 09:28 UTC, closed without merging

2022-05-06 09:31 UTC, mart-ffbsee commented on files/etc/uci-defaults/50_freifunk-setup
> +update_230() {
die Benamung bezieht sich darauf welche Version upgedatet wird. Da es keine 2.4.0 im Einsatz gibt, kann man die auch nicht updaten.